### PR TITLE
Remove customisation of actions.

### PR DESCRIPTION
**Pull request by busykoala**
Before:
image

After:
image

### CODE REVIEW

**Review by tinagerber — CHANGES_REQUESTED** [review]
Looks good. But the `Test whether tests run.` commit  seems to be a bit superfluous 😄
Can you add a changelog entry?

**Review by maethu — APPROVED** [review]
The change is fine, since bern.ch does not have any document actions :-) and they are now rendered within the content area, so there is no need for this rule 👍

**Comment by busykoala** [comment]
@tinagerber I added a changelog and removed the superfluous commit.

**Review by tinagerber — APPROVED** [review]
🦄super

**Pull request merged**
