### PR TITLE
Implement ajax loading spinner.

### PR DESCRIPTION
**Pull request by bierik**
Plone has a built in ajax spinner that is triggered for every ajax
request. This implementation replaces the default behaviour. It is now
possible to define which request should display a spinner and how long
is the loading tolerance before a spinner is shown.

### CODE REVIEW

**Comment by bierik** [comment]
@maethu updated

**Comment by jone** [comment]
How can I change the behavior?

**Comment by bierik** [comment]
See https://github.com/OneGov/plonetheme.onegovbear/blob/kb_spinner/plonetheme/onegovbear/theme/js/spin.js#L6

**Comment by bierik** [comment]
@maethu tests fixed

**Comment by bierik** [comment]
@maethu was ist mit dem?

**Comment by bierik** [comment]
Implementation done in https://github.com/4teamwork/ftw.simplelayout/pull/339

**Pull request closed without merging**
